### PR TITLE
Change es get/set to synchronized and fixed test cases

### PR DESCRIPTION
**Pull request by hankok**
Hi Tong,

I changed the elasticsearch actions to synchronized. And all the alarmdefination and notification methods are stored in an index named "admin".
One question is will alarms be stored in data_2015... or admin index?
Another question is I can't get pep8 pass on one line of the test cases where "with expressions " with multiple patch objects are used. e.g.

        with mock.patch.object(notifications.NotificationMethodDispatcher,
                               'handle_notification_msg',
                               return_value=200), \
             mock.patch.object(ast, 'literal_eval',
                               return_value=ast.literal_eval(
                                   "{'type': 'PAGEDUTY', "
                                   "'name': 'NotificationMethod2', "
                                   "'address': '1234567'}")):

The error is monasca/tests/v2/elasticsearch/test_notification.py:185:51: H904  Wrap long lines in parentheses instead of a backslash
                               return_value=200), \

I don't know how to change it to (), because parentheses will make the with expression invalid.

Thanks,
Han

### CODE REVIEW

**Comment by litong01** [comment]
see this example:

    def test_do_put_alarm_definitions(self):
        l_val = ast.literal_eval(
            "{'name':'CPU usage test', "
            "'alarm_actions': "
            "'c60ec47e-5038-4bf1-9f95-4046c6e9a719',"
            "'undetermined_actions': "
            "'c60ec47e-5038-4bf1-9t95-4046c6e9a759', "
            "'ok_actions': "
            "'c60ec47e-5038-4bf1-9f95-4046cte9a759', "
            "'match_by': 'hostname', "
            "'severity': 'LOW', "
            "'expression': "
            "'max(cpu.usage{os=linux},600)>15', "
            "'description': 'The max CPU percent'"
            "'in last 10 min is greater than 15'}")
        with (mock.patch.object(kafka_conn.KafkaConnection, 'send_messages',
                                return_value=204),
              mock.patch.object(ast, 'literal_eval',
                                return_value=l_val)):
            res = mock.Mock()
            self.dispatcher_post.do_put_alarm_definitions(
                mock.Mock(), res, id="72df5ccb-ec6a-4bb4-a15c-939467ccdde0")
        self.assertEqual(getattr(falcon, 'HTTP_204'), res.status)

**Comment by litong01** [comment]
I am trying to figure out this syntax myself. I do not think that will work.

**Comment by litong01** [comment]
I did a bit more digging, here is what I can find. This will certainly work. Basically use nested with. Here is an example.

        with mock.patch.object(es_conn.ESConnection,
                               'put_messages',
                               return_value=204):
            with mock.patch.object(ast, 'literal_eval',
                                   return_value=l_val):

**Comment by hankok** [comment]
Thanks a lot, i will try it.
Sent from my phone
在 litong01 <notifications@github.com>，2015年6月30日 下午1:08写道：I did a bit more digging, here is what I can find. This will certainly work. Basically use nested with. Here is an example.

    with mock.patch.object(es_conn.ESConnection,
                           'put_messages',
                           return_value=204):
        with mock.patch.object(ast, 'literal_eval',
                               return_value=l_val):

**Pull request closed without merging**
